version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    ports: 
      - "8080:8080"
    volumes:
      - "/home/tupi/jenkins/jenkins-data/jenkins_home:/var/jenkins_home"
    networks:
      - net-jenkins
  remote-host:
    container_name: remote-host
    image: remote-host:latest
    build:
      context: centos7
    volumes:
      - "/home/tupi/jenkins/jenkins-data/sqlbak.sh:/tmp/sqlbak.sh:ro"
    networks:
      - net-jenkins
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "/home/tupi/jenkins/jenkins-data/db_data:/var/lib/mysql"
    networks:
      - net-jenkins
networks:
  net-jenkins:
