version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - "8080:8080"
    volumes:
      - "/home/tupi/jenkins/jenkins-data/jenkins_home:/var/jenkins_home:z"
    networks:
      - net-jenkins
networks:
  net-jenkins:

